---
galaxy_info:
  namespace: community
  author: IBM Lab for SAP Solutions, Red Hat for SAP Community of Practice, Jason Masipiquena, Sean Freeman
  description: Installation of SAP Software using the SAP Software Provisioning Manager (SWPM) on Linux OS (RHEL, SLES)
  license: Apache-2.0
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions: [ 7, 8, 9 ]
    - name: SLES
      versions: [ 15SP3 ]
  galaxy_tags: [ 'sap', 'swpm', 'sapinst', 'rhel', 'redhat', 'sles', 'suse' ]
dependencies: []
