---

# Copy reused inifile
- name: SAP SWPM inifile_reuse mode - Copy reused inifile
  ansible.builtin.copy:
    src: "{{ sap_swpm_inifile_reuse_source }}"
    dest: "{{ sap_swpm_tmpdir.path }}/inifile.params"
    mode: '0640'
  tags: sap_swpm_generate_inifile

# Check inifile for the presence of a line containing "des25("
- name: SAP SWPM inifile_reuse mode - Check inifile for des25
  ansible.builtin.shell: |
    set -o pipefail && cat "{{ sap_swpm_tmpdir.path }}/inifile.params" |
    awk 'BEGIN{a=0}!/^#/&&/des25\(/{a++}END{print a}'
  register: sap_swpm_inifile_read_file
  changed_when: false
  tags: sap_swpm_generate_inifile

# Check if inifile is reusable - function des25 must not be present in inifile
- name: SAP SWPM inifile_reuse mode - Check if inifile is reusable, meaning function des25 is not present
  ansible.builtin.fail:
    msg: "{{ sap_swpm_inifile_reuse_source }} is not reusable"
  when: sap_swpm_inifile_read_file.stdout != '0'
  tags: sap_swpm_generate_inifile

# Detect variables from generated inifile
- name: SAP SWPM inifile_reuse mode - Detect Variables
  ansible.builtin.include_tasks:
    file: detect_variables.yml
    apply:
      tags: sap_swpm_generate_inifile
  tags: sap_swpm_generate_inifile

# Requires variables - sap_swpm_software_path (e.g. /software/download_basket), sap_swpm_sapcar_path (e.g. /software/sapcar), sap_swpm_swpm_path (e.g. /software/swpm)
# Prepare Software
- name: SAP SWPM inifile_reuse mode - Prepare Software
  ansible.builtin.include_tasks: prepare_software.yml
