---
cluster_totem:
  token: 30000
  retransmits: 10
  join: 60
  consensus: 36000
  max_messages: 20

cluster_quorum:
  expected_votes: 2
  two_node: 1

# These are the default timeouts used for the SAP SCS OS clustering. Depending on the
# SAP SCS System, these may need to be adjusted if the operation takes longer than expected.
cluster_sap_scs_timeouts:
  start:          60s
  stop:           60s
  monitor_master: 700
  monitor_slave: 700
  promote: 3600
  demote: 3600

cluster_status_cmd:
  RedHat: "pcs status --full"
  Suse: "crm status full"

cluster_status_report_wait_in_s: 60

# SCS/ERS SID/Instance Numbers
sap_domain: 'nonprod.pce.cloud'
scs_instance_number: "01"
ers_instance_number: "02"
sid: "QP1"
primary_instance_name: "vmplrqp1ascs"
secondary_instance_name: "vmplrqp1ers"
sap_mnt: "10.111.16.68:/QP1APP"
sap_sid: "QP1"
scs_lb_ip: "10.111.16.17"
ers_lb_ip: "10.111.16.16"
password_ha_db_cluster: "Welcome123"
sap_fqdn: "nonprod.pce.cloud"
subnet_prefix: "25"
instance_type: "ASCS"
clus_sap_mon_timeout: 60
sid: "QP1"
sap_sid: "QP1"
db_sid: "QP1" 
db_instance_number: "00" 
db_lb_ip: "10.111.17.25"
sap_swpm_sid: "{{ sid }}"

#cluster_variables move these to group vars########
resource_group_name: "rg-pce-sap-qa-gwc-001"
sap_hana_fencing_agent_subscription_id: "69e0eaf7-cc5d-47b8-a5c6-c93d4e4bb57b"                                         

#sap_hana_fencing_agent_tenant_id: ""

# Virtual Host Names
scs_virtual_hostname: "{{ sap_sid | lower }}scs{{ scs_instance_number }}vip1"
ers_virtual_hostname: "{{ sap_sid | lower }}ers{{ ers_instance_number }}vip2"


# The following values should be same as iSCSI configuration
# run 'sudo targetcli ls' on iSCSI target virtual machines to get all iSCSI configuration
cluster_name: qp1hacluster   # nw{{ sid | lower }}
# storage_object: sbd{{ cluster_name }}
# target: "{{ iscsi_object }}.{{ cluster_name }}.local:{{ cluster_name }}"

# SAP ASCS/ERS Utility Commands
sapcontrolscs_command: "sapcontrol -nr {{ scs_instance_number }}"
sapcontrolers_command: "sapcontrol -nr {{ ers_instance_number }}"

# hana_stop_start_timeout_in_seconds: 2700
# hana_stop_start_delay_in_seconds: 2

primary_instance:
  name: "{{hostvars[groups['hanadbnodes'][0]].ansible_facts.hostname}}"
  ip_admin: "{{ hostvars[groups['hanadbnodes'][0]].ansible_facts.default_ipv4.address }}"
  ip_db: "{{ hostvars[groups['hanadbnodes'][0]].ansible_facts.default_ipv4.address }}"
secondary_instance:
  name: "{{hostvars[groups['hanadbnodes'][1]].ansible_facts.hostname}}"
  ip_admin: "{{ hostvars[groups['hanadbnodes'][1]].ansible_facts.default_ipv4.address }}"
  ip_db: "{{ hostvars[groups['hanadbnodes'][1]].ansible_facts.default_ipv4.address }}"




...

