---
# General parameters
swap_size_mb: "2052"

# Volume groups and logical volumes
# vgs:
# # SAP VG
# - name: sapvg
#   lvs:
#   - name: usrsaplv
#     path: /usr/sap/
#     size: 20G
#   - name: sapmntlv
#     path: /sapmnt/
#   pvs:
#   - "/dev/disk/azure/scsi1/lun0"

# azure_storage_mounts:
# - share_name: 
#   storage_account_name: 
#   resource_group_name: 
#   subscription_id: 
#   path: 
#   file_mode: 0777
#   dir_mode: 0777
# - share_name: 
#   storage_account_name: 
#   resource_group_name: 
  # subscription_id: 
  # path: 
  # file_mode: 0777
  # dir_mode: 0777

# Product ID for New Installation. Example for backup/restore: NW_ABAP_OneHost:S4HANA2021.CORE.HDB.CP
sap_swpm_product_catalog_id: NW_Webdispatcher:NW750.IND.PD

# Software
sap_swpm_software_path: /software/Webdispatcher_media/
sap_swpm_sapcar_path: /software/Webdispatcher_media/
sap_swpm_swpm_path: /software/Webdispatcher_media/

# NW Passwords
sap_hana_install_master_password: Plrsap@321
sap_swpm_master_password: "{{ sap_hana_install_master_password }}"

# Misc
sap_swpm_delete_sapinst_users: "true"
sap_swpm_wd_use_wd_http_port: "true"
sap_swpm_sapadm_uid: "1002"
sap_swpm_sapsys_gid: "1002"
sap_swpm_sidadm_uid: "1001"
sap_swpm_set_fqdn: false
sap_swpm_fqdn: ""
sap_swpm_setup_firewall: yes

# NW Instance Parameters
sap_swpm_sid: "DW1"
sap_swpm_wd_instance_nr: "00"

# Backend Connection
sap_swpm_wd_system_connectivity: 'true'
sap_swpm_wd_activate_icf: 'false'
sap_swpm_wd_backend_sid: "DP1"
sap_swpm_wd_backend_ms_http_port: "8101"
sap_swpm_wd_backend_ms_host: "vmplrdp1app"
sap_swpm_wd_backend_rfc_host: "vmplrdp1app"
sap_swpm_wd_backend_rfc_instance_nr: "00"
sap_swpm_wd_backend_scenario_size: "500"
# sap_swpm_wd_backend_rfc_client_nr: "000"
# sap_swpm_wd_backend_rfc_user: "DDIC"
# sap_swpm_wd_backend_rfc_user_password: "NewPass$321"
sap_swpm_wd_virtual_host: "vmplrdw1app" # Change it to  Hostname of the actual server

# SAP Host Agent
sap_swpm_install_saphostagent: 'false'

# Generate inifile.params using sap_swpm Ansible Role
sap_swpm_inifile_list:
  - swpm_installation_media
  - credentials
  - nw_config_other
  # - nw_config_central_services_abap
  # - nw_config_primary_application_server_instance
  # - nw_config_ports
  - nw_config_webdisp_generic
  # - nw_config_host_agent
  - sap_os_linux_user



