---
# General parameters
# swap_size_mb: "20520"
# sap_solution: NETWEAVER

# Azure Storage mounts
# azure_storage_mounts:
# - share_name: heifsmedia
#   storage_account_name: heisapstorage01
#   resource_group_name: hei-coregc-rg-sap-weeu-infra
#   subscription_id: 4f50e73b-0f78-469d-8948-584b0ecb0342
#   path: /share/heifsmedia
#   file_mode: "0775"
#   dir_mode: "0775"
# - share_name: heifsbackup
#   storage_account_name: heisapstorage01
#   resource_group_name: hei-coregc-rg-sap-weeu-infra
#   subscription_id: 4f50e73b-0f78-469d-8948-584b0ecb0342
#   path: /share/heifsbackup
#   file_mode: "0775"
#   dir_mode: "0775"
# - share_name: heifsdepmedia
#   storage_account_name: heidepstorage01
#   resource_group_name: hei-coregc-rg-dep-weeu-saplibrary
#   subscription_id: 48b7643a-5031-4970-9fcf-873eb22ed08c
#   path: /share/heifsdepmedia
#   file_mode: "0775"
#   dir_mode: "0775"
# - share_name: heifstrans-d1c
#   storage_account_name: heisapstorage01
#   resource_group_name: hei-coregc-rg-sap-weeu-infra
#   subscription_id: 4f50e73b-0f78-469d-8948-584b0ecb0342
#   path: /usr/sap/trans
#   file_mode: "0777"
#   dir_mode: "0777"
  # gid: "79"
  # uid: "2024"
  
  
# Volume groups and logical volumes
# vgs:
# # SAP VG
# - name: sapvg
#   lvs:
#   - name: usrsaplv
#     path: /usr/sap/
#     size: 255G

  # sapmnt will be mounted via azure netapps  
  #- name: sapmntlv
  #  path: /sapmnt/
  # pvs:
  # - "/dev/disk/azure/scsi1/lun0"

# Product ID for New Installation. Example for backup/restore: NW_ABAP_OneHost:S4HANA2021.CORE.HDB.CP

# sap_swpm_product_catalog_id: NW_ABAP_CI:S4HANA2022.CORE.HDB.ABAPHA
sap_swpm_product_catalog_id: NW_ABAP_CI:S4HANA2022.CORE.HDB.HACP

# Software
# sap_swpm_software_path: /share/heifsdepmedia/S4HANA2022FPS00/
# sap_swpm_sapcar_path: /share/heifsdepmedia/S4HANA2022FPS00/
# sap_swpm_swpm_path: /share/heifsdepmedia/S4HANA2022FPS00/

sap_swpm_software_path: /software/S4_media/
sap_swpm_sapcar_path: /software/HCMT_tool/
sap_swpm_swpm_path: /software/S4_media/


# NW Instance Parameters
sap_swpm_fqdn: "nonprod.pce.cloud"
sap_swpm_delete_sapinst_users: "true"
sap_swpm_setup_firewall: yes

sap_swpm_sid: "QP1"
sap_swpm_ascs_instance_nr: "01"
sap_swpm_ascs_instance_hostname: "vmplrqp1ascs"
sap_swpm_ascs_instance_ip: "10.222.16.13"
sap_swpm_ers_instance_nr: "02"
sap_swpm_ers_instance_hostname: "vmplrqp1ers"
sap_swpm_ers_instance_ip: "10.222.16.14"
sap_swpm_pas_instance_nr: "00"
sap_swpm_pas_instance_hostname: "vmplrqp1app1"
sap_swpm_pas_instance_ip: "10.222.16.15"
sap_swpm_aas_instance_nr: "03"
sap_swpm_aas_instance_hostname: "vmplrqp1app2"
sap_swpm_aas_instance_ip: "10.222.16.16"


# # HDB Instance Parameters
# # For dual host installation, change the db_host to appropriate value.Maintain /etc/hosts file for both db and app.
# sap_swpm_db_host: "heip1hhdb05z2"
# sap_swpm_db_ip: "10.178.40.133"
# sap_swpm_db_host_secondary: "heip1hhdb05z3"
# sap_swpm_db_ip_secondary: "10.178.40.134"
# sap_swpm_db_sid: "P1H"
# sap_swpm_db_instance_nr: "05"

# HDB Instance Parameters
# For dual host installation, change the db_host to appropriate value.Maintain /etc/hosts file for both db and app.
sap_swpm_db_host: "vmplrqp1hana1"
sap_swpm_db_sid: "QP1"
sap_swpm_db_instance_nr: "00"
sap_swpm_db_schema_abap: "SAPHANADB"

# Virtual Ips
scs_lb_ip: "10.222.16.17"
ers_lb_ip: "10.222.16.20"
db_lb_ip: "10.222.17.37"


# Virtual Host Names
scs_virtual_hostname: "{{ sap_swpm_sid | lower }}scs{{ sap_swpm_ascs_instance_nr }}vip1"
ers_virtual_hostname: "{{ sap_swpm_sid | lower }}ers{{ sap_swpm_ers_instance_nr }}vip2"
db_virtual_hostname: "{{ sap_swpm_db_sid | lower }}hdb{{ sap_swpm_db_instance_nr }}vip1"

# NW Passwords
sap_app_install_master_password: "Plrsap@321"
sap_swpm_master_password: "{{ sap_app_install_master_password }}"
sap_swpm_ddic_000_password: "{{ sap_app_install_master_password }}"
sap_swpm_java_export_keyphrase: "{{ sap_app_install_master_password }}"

# HDB Passwords
sap_hana_install_master_password: "Plrhana@321"
sap_swpm_db_system_password: "{{ sap_hana_install_master_password }}"
sap_swpm_db_systemdb_password: "{{ sap_hana_install_master_password }}"
# sap_swpm_db_schema_java: "SAPJAVA1"
sap_swpm_db_schema_password: "{{ sap_hana_install_master_password }}"
sap_swpm_db_schema_java_password: "{{ sap_hana_install_master_password }}"
sap_swpm_db_sidadm_password: "{{ sap_hana_install_master_password }}"

# # Need to define:
# sap_swpm_java_export_keyphrase: ""
# sap_swpm_use_product_version_descriptor: ""
# sap_swpm_unpack_igs_exe_sar: ""
# sap_swpm_unpack_igs_helper_sar: ""
# sap_swpm_unpack_sap_exe_sar: ""
# sap_swpm_unpack_sap_jvm_sar: ""

# # HDB Passwords
main_password: "{{ sap_hana_install_master_password }}"


# inifile_reuse
sap_swpm_ansible_role_mode: "default"

# # HDB Passwords
sap_swpm_db_schema_abap: "SAPHANADB"
main_password: "{{ sap_hana_install_master_password }}"

# DB Restore Parameters
# sap_swpm_backup_location: "/share/heifsdepmedia/Q2C_S42021_FPS02_BLK_ADDON_FIORI_CONFIG_GF_12102022/DB_Q2H/"
# sap_swpm_backup_prefix: COMPLETE_DATA_BACKUP

# DB Restore Parameters Backup from AUG 24-2023 (S4HANA2022.CORE.HDB.CP) - S4HANA2022FPS01FIORI
# sap_swpm_backup_location: "/share/heifsbackup/D4HGOLDENBACKUP_DECRYPTED/"
# sap_swpm_backup_prefix: COMPLETE_DATA_BACKUP


# Unix User ID
sap_swpm_sapadm_uid: '1002'
sap_swpm_sapsys_gid: '1002'
sap_swpm_sidadm_uid: '1001'
sap_swpm_update_etchosts: 'false'

# SWPM parameters
sap_swpm_inifile_list:
  - installation_media
  - swpm_installation_media
  - credentials
  - credentials_hana
  - db_config_hana
  - nw_config_central_services_abap
  - db_config_anydb_all
  - db_connection_nw_hana
  #- db_hana_restore
  - db_restore_hana #(Uncomment of backup/restore is required)
  - nw_config_primary_application_server_instance
  - db_hana_nw_connection
  - nw_config_other
  - nw_other_config
  - nw_instance_config
  - unix_user
  - other
  - db_hana_high_isolation
  - credentials_hana

# HA Defaults

sap_swpm_virtual_hostname: "{{ sap_swpm_pas_instance_hostname }}"

# Azure NetApps

sap_ha_set_netweaver_role: pas
sap_ha_set_netweaver_sid: "{{ sap_swpm_sid }}"
sap_ha_set_netweaver_ascs_instance_nr: "{{ sap_swpm_ascs_instance_nr }}"
sap_ha_set_netweaver_ers_instance_nr: "{{ sap_swpm_ers_instance_nr }}"
sap_ha_set_netweaver_pas_instance_nr: "{{ sap_swpm_pas_instance_nr }}"
# sap_hasap_ha_set_netweaver_nfs_mount_path_name: p1cprdshr
# sap_ha_set_netweaver_nfs_ip: 10.178.41.4

# Var for GWC IP for netapps
sap_hasap_ha_set_netweaver_nfs_mount_path_name: p1cprdsdr
sap_ha_set_netweaver_nfs_ip: 10.182.26.68


# NW Passwords
sap_swpm_master_password: "{{ sap_hana_install_master_password }}"
sap_swpm_ddic_000_password: "{{ sap_hana_install_master_password }}"



# HDB Passwords
# sap_swpm_db_system_password: "{{ sap_hana_install_master_password }}"
# sap_swpm_db_systemdb_password: "{{ sap_hana_install_master_password }}"
# sap_swpm_db_schema_abap_password: "{{ sap_hana_install_master_password }}"
# sap_swpm_db_sidadm_password: "{{ sap_hana_install_master_password }}"
# sap_swpm_db_schema_abap: "SAPHANADB"


  
