---
# General parameters
swap_size_mb: "20640"
sap_solution: NETWEAVER

# azure_storage_mounts:
# - share_name: 
#   storage_account_name: 
#   resource_group_name: 
#   subscription_id: 
#   path: 
#   file_mode: 775
#   dir_mode: 775
# - share_name: 
#   storage_account_name: 
#   resource_group_name: 
#   subscription_id: 
#   path: 
#   file_mode: 775
#   dir_mode: 775

# # Volume groups and logical volumes
# vgs:
# # SAP VG
# - name: sapvg
#   lvs:
#   - name: usrsaplv
#     path: /usr/sap/
#     size: 40G
#   - name: sapmntlv
#     path: /sapmnt/
#   pvs:
#   - "/dev/disk/azure/scsi1/lun0"

# Software
sap_swpm_software_path: /software/ADS_media/
sap_swpm_sapcar_path: /software/ADS_media/
sap_swpm_swpm_path: /software/ADS_media/
sap_swpm_unpack_igs_exe_sar: /software/ADS_media/igsexe_4-80007786.sar
sap_swpm_unpack_igs_helper_sar: /software/ADS_media/igshelper_17-10010245.sar
sap_swpm_unpack_sap_exe_sar: /software/ADS_media/SAPEXE_201-80007612.SAR
sap_swpm_unpack_sap_jvm_sar: /software/ADS_media/SAPJVM8_97-80000202.SAR
sap_swpm_cd_rdms_path: /software/ADS_media
sap_swpm_cd_java_path: /software/ADS_media
sap_swpm_cd_export_path: /software/ADS_media/HANA2.76/51055106
sap_swpm_cd_export_pt1_path: /software/ADS_media/HANA2.76/51055106
sap_swpm_cd_export_pt2_path: /software/ADS_media/HANA2.76/51055106

# SAP SWPM Variables
sap_swpm_product_catalog_id: NW_Java_OneHost:NW750.HDB.PD
sap_swpm_db_schema: SAPJAVA1
sap_swpm_software_use_media: "false"
sap_swpm_delete_sapinst_users: "true"
sap_swpm_sapadm_uid: "1002"
sap_swpm_sapsys_gid: "1002"
sap_swpm_sidadm_uid: "1001"
sap_swpm_setup_firewall: yes
sap_swpm_use_product_version_descriptor: "true"
sap_swpm_software_use_media: "false"

# NW Instance Parameters
sap_swpm_sid: DA1
sap_swpm_pas_instance_nr: "00"
sap_swpm_java_scs_instance_nr: "01"
sap_swpm_pas_instance_hostname: "{{ ansible_hostname }}"
sap_swpm_ascs_instance_hostname: "{{ ansible_hostname }}"
sap_swpm_java_scs_instance_hostname: "{{ ansible_hostname }}"
sap_swpm_set_fqdn: "false"
sap_swpm_fqdn: ""
sap_swpm_load_type: SAP

# HDB Instance Parameters
sap_swpm_db_host: vmplrda1hana
sap_swpm_db_schema_java: SAPJAVA1
sap_swpm_db_sid: DA1
sap_swpm_db_instance_nr: "00"

# NW Passwords
sap_app_install_master_password: "Plrsap@321"
sap_swpm_master_password: "{{ sap_app_install_master_password }}"
sap_swpm_ddic_000_password: "{{ sap_app_install_master_password }}"
sap_swpm_java_export_keyphrase: "{{ sap_app_install_master_password }}"

# HDB Passwords
sap_hana_install_master_password: "Plrhana@321"
sap_swpm_db_system_password: "{{ sap_hana_install_master_password }}"
sap_swpm_db_systemdb_password: "{{ sap_hana_install_master_password }}"
sap_swpm_db_schema_java: "SAPJAVA1"
sap_swpm_db_schema_password: "{{ sap_hana_install_master_password }}"
sap_swpm_db_schema_java_password: "{{ sap_hana_install_master_password }}"
sap_swpm_db_sidadm_password: "{{ sap_hana_install_master_password }}"


# UME Parameters
sap_swpm_ume_type: "abap"
sap_swpm_ume_j2ee_admin_password: "{{ sap_app_install_master_password }}"
sap_swpm_ume_sapjsf_password: "{{ sap_app_install_master_password }}"
sap_swpm_ume_client_nr: "000"
sap_swpm_ume_instance_nr: "{{ sap_swpm_pas_instance_nr }}"
sap_swpm_ume_instance_hostname: "{{ ansible_hostname }}"

# Generate inifile.params using sap_swpm Ansible Role
sap_swpm_inifile_list:
  - swpm_installation_media
  # - swpm_installation_media_swpm1
  - swpm_installation_media_swpm1_exportfiles
  - installation_media
  - credentials
  - credentials_hana
  - db_config_hana
  - db_connection_nw_hana
  #- db_hana_nw_connection
  - nw_config_java_ume
  - nw_config_central_services_java
  - nw_config_primary_application_server_instance
  - nw_config_other
  #- nw_other_config
  #- db_restore_hana     #(Uncomment if backup is required)  
  - nw_instance_config
  - sap_os_linux_user
  - other
  #- db_hana_high_isolation
