---

- name: SAP SWPM - run pre_install tasks
  ansible.builtin.import_tasks: pre_install.yml
  tags:
    - sap_swpm_pre_install
    - sap_swpm_install

- name: SAP SWPM - run swpm
  ansible.builtin.import_tasks: swpm.yml
  tags:
    - sap_swpm_install

- name: SAP SWPM - run postinstall task
  ansible.builtin.import_tasks: post_install.yml
