---

- name: SAP SWPM Pre Install - Remove existing {{ sap_swpm_sid | lower + 'adm' }}
  block:

# Reason for noqa: We currently do not determine if there are processes to be killed
    - name: SAP SWPM Pre Install - Kill all processes under {{ sap_swpm_sid | lower + 'adm' }}
      ansible.builtin.shell: |
        killall -u {{ sap_swpm_sid | lower }}adm
      ignore_errors: yes
      changed_when: true

    - name: SAP SWPM Pre Install - Remove user {{ sap_swpm_sid | lower + 'adm' }}
      ansible.builtin.user:
        name: '{{ sap_swpm_sid | lower }}adm'
        state: absent
        remove: yes
        force: yes

    - name: SAP SWPM Pre Install - Remove group {{ sap_swpm_sid | lower + 'adm' }}
      ansible.builtin.group:
        name: '{{ sap_swpm_sid | lower }}adm'
        state: absent

- name: SAP SWPM Pre Install - Create sapsys group
  ansible.builtin.group:
    name: 'sapsys'
    gid: '{{ sap_swpm_sapsys_gid }}'
    state: present

- name: SAP SWPM Pre Install - Create {{ sap_swpm_sid | lower + 'adm' }}
  ansible.builtin.user:
    name: '{{ sap_swpm_sid | lower }}adm'
    comment: "SAP User - {{ sap_swpm_sid }}"
    password: "{{ sap_swpm_master_password | password_hash('sha512') }}"
    uid: '{{ sap_swpm_sidadm_uid }}'
    group: '{{ sap_swpm_sapsys_gid }}'
    shell: /bin/csh

- name: SAP SWPM Pre Install - Create a /usr/sap/{{ sap_swpm_sid }}
  ansible.builtin.file:
    path: /usr/sap/{{ sap_swpm_sid }}
    state: directory
    owner: '{{ sap_swpm_sid | lower }}adm'
    group: sapsys
    recurse: yes
    mode: '0755'

- name: SAP SWPM Pre Install -  ASCS Cluster / Install ASCS on Primary host 
  block: 
  - name: "SCSERS - SCS - Assign ownership"
    ansible.builtin.file:
      path: "{{ item.path }}"
      state: directory
      owner: '{{ sap_swpm_sid | lower }}adm'
      group: sapsys
      recurse: yes
      mode: '0755'
    loop:
      - { path: '/sapmnt/{{ sap_swpm_sid | upper }}' }
      - { path: '/usr/sap/{{ sap_swpm_sid | upper }}/SYS' }
      - { path: '/usr/sap/{{ sap_swpm_sid | upper }}/ASCS{{ sap_swpm_ascs_instance_nr }}' }
     
  when: inventory_hostname == sap_swpm_ascs_instance_hostname

- name: SAP SWPM Pre Install - ASCS Cluster / Install ERS on Primary host 
  block: 
  - name: "SCSERS - ERS - Assign ownership"
    ansible.builtin.file:
      path: "{{ item.path }}"
      state: directory
      owner: '{{ sap_swpm_sid | lower }}adm'
      group: sapsys
      recurse: yes
      mode: '0755'
    loop:
      - { path: '/sapmnt/{{ sap_swpm_sid | upper }}' }
      - { path: '/usr/sap/{{ sap_swpm_sid | upper }}/SYS' }
      - { path: '/usr/sap/{{ sap_swpm_sid | upper }}/ERS{{ sap_swpm_ers_instance_nr }}' }  

  when: inventory_hostname == sap_swpm_ers_instance_hostname   
