---
- name: "SAP Pacemaker Hana - Add sudo"
  template:
    backup: yes
    dest: /etc/sudoers.d/20-saphana
    mode: "0440"
    owner: root
    group: root
    src: templates/20-saphana.j2
    