---

###########################################################################################
# This file calls the OS specific tasks to configure HANA specific clustering resources  #8
###########################################################################################


# Clustering commands are based on the Host OS
- name:                                Cluster based on OS in VM
  ansible.builtin.include_tasks:       "cluster-{{ ansible_os_family }}.yml"

...
