---

- name: SAP SWPM Pre Install - Determine Installation Type
  ansible.builtin.set_fact:
    sap_swpm_swpm_installation_type: ""
    sap_swpm_swpm_installation_header: ""
    sap_swpm_swpm_command_virtual_hostname: ""
    sap_swpm_swpm_command_mp_stack: ""

################
# Determine Installation Type
################

# Ignore Product IDs for SAP NetWeaver 7.5 Java standalone:
# - Advanced Adapter Engine (AE) with .AE .AEHA
# - Advanced Adapter Engine Extended (AEX) with .AEX .AEXHA
# - Process Integration / Process Orchestration (PI/PO) with .PI .PIHA .PIABAP .PIABAPHA .PIJAVA .PIJAVAHA

#- name: SAP SWPM Pre Install - Check if general SAP Software installation
#  ansible.builtin.set_fact:
#    sap_swpm_swpm_installation_type: "general"
#    sap_swpm_swpm_installation_header: "General installation of SAP Software"
#  when:
#    - "not '.ABAPHA' in sap_swpm_product_catalog_id"
#    - "not '.CP' in sap_swpm_product_catalog_id"

- name: SAP SWPM Pre Install - Check if System Copy (Backup/Restore)
  ansible.builtin.set_fact:
    sap_swpm_swpm_installation_type: "restore"
    sap_swpm_swpm_installation_header: "System Copy restore from backup"
  when:
    - "'.CP' in sap_swpm_product_catalog_id"

- name: SAP SWPM Pre Install - Check if SAP High Availability installation
  ansible.builtin.set_fact:
    sap_swpm_swpm_installation_type: "ha"
    sap_swpm_swpm_installation_header: "High Availability Installation using virtual hostname"
  when:
    - "'.ABAPHA' in sap_swpm_product_catalog_id or '.HA' in sap_swpm_product_catalog_id or '.HACP' in sap_swpm_product_catalog_id"

- name: SAP SWPM Pre Install - Check if installation using SAP Maintenance Planner
  ansible.builtin.set_fact:
    sap_swpm_swpm_installation_type: "maint_plan_stack"
    sap_swpm_swpm_installation_header: "Installing using SAP Maintenance Planner Stack XML"
  when:
    - sap_swpm_mp_stack_path is defined and not sap_swpm_mp_stack_path is none

- name: SAP SWPM Pre Install - Check if SAP High Availability installation and using SAP Maintenance Planner
  ansible.builtin.set_fact:
    sap_swpm_swpm_installation_type: "ha_maint_plan_stack"
    sap_swpm_swpm_installation_header: "High Availability Installation using virtual hostname and SAP Maintenance Planner Stack XML"
  when:
    - "'.ABAPHA' in sap_swpm_product_catalog_id"
    - sap_swpm_mp_stack_path is defined and not sap_swpm_mp_stack_path is none

################
# Run Installation Type Steps
################

- name: SAP SWPM Pre Install - Display the Installation Type
  ansible.builtin.debug:
    var: sap_swpm_swpm_installation_type

- name: SAP SWPM Pre Install - Run Installation Type Steps
  ansible.builtin.include_tasks: "install_type/{{ sap_swpm_swpm_installation_type }}_install.yml"
  when: "sap_swpm_swpm_installation_type | length > 0"
