---
- hosts: all   # sap_s4hana , sap_hana , sap_webdispatcher, sap_nw_java_ads, sap_hana_ads , sap_ascs , sap_ers
  max_fail_percentage: 0
  tasks:
  - name: stop Firewalld
    become: yes
    ansible.builtin.shell: |
      systemctl stop firewalld
      
  - name: Disable Firewalld
    become: yes
    ansible.builtin.shell: |
      systemctl disable firewalld
