---
- hosts: sap_hana
  max_fail_percentage: 0
  serial: 1  
  tasks:
    - name: SAP NW HA - Update SAP HANA secure store
      shell: |
        /usr/sap/{{ sap_hana_install_sid | upper}}/SYS/exe/hdb/hdbuserstore \
        SET DEFAULT {{ db_virtual_hostname }}:3{{ db_instance_number }}13@{{ sap_hana_install_sid  | upper }} {{ sap_swpm_db_schema_abap }} '{{ sap_ha_install_hana_hsr_db_system_password }}'
      args:
        executable: /bin/bash
      ignore_errors: yes
      become: true
      become_user: "{{ sap_hana_install_sid  | lower }}adm"


     
      
  
