---
- name: Webdisaptcher Status
  hosts: sap_webdispatcher
  become: true
  vars:
    SID: dw1
    webdispatcher_port:
    sapcontrol_path: /software/Webdispatcher_media/
  tasks:
    - name: show SID number(s) for AS
      debug:
        msg: "{{ SID }}"

    - name: collect instance number(s) for AS
      shell:
        cmd: /usr/sap/hostctrl/exe/lssap | awk -v sid={{ SID |upper }} -F'|' '{gsub(" ","");if ($1=="{{ SID|upper }}") print $2}' | sort
      register: instance_nr

    - debug: var=instance_nr
    
    - name: initialise empty array
      set_fact:
        instance_nr_lines: []
    
    - name: create fact that will use instance_nr_lines array
      set_fact:
        instance_nr_lines: "{{ instance_nr_lines  + [ item  ] }}"
      loop: "{{ instance_nr.stdout_lines }}"
    
    - name: show instance numbers, line-by-line
      debug:
        msg: "{{ item }}"
      loop: "{{ instance_nr_lines }}"
    
    - name: Status Of Webdisaptcher
      shell:
        cmd: /bin/csh -c "sapcontrol -nr {{ instance_nr_lines[0] }} -function GetProcessList"
      become: yes
      become_user: "{{ SID|lower }}adm"
      register: extra_check_result
      ignore_errors: true
    
    - name: Display of Status Of Webdisaptcher
      debug:
        msg: "{{ extra_check_result }}"
      when: '"GRAY" not in extra_check_result.stdout_lines and "YELLOW" not in extra_check_result.stdout_lines and "RED" not in extra_check_result.stdout_lines'
      
    - name: Fail message when Status is not GREEN
      fail:
        msg: "Webdisaptcher status is not GREEN"
      when: "'GREEN' in extra_check_result.stdout_lines"
      
    - name: Check the Process
      shell: "ps -ef | grep {{ SID |lower }}adm"
      register: ps_ef_ouptut

    - name: setfact for ps ef
      setfact:
        ws_sap: "wd.sap{{ SID|lower }}_W{{ instance_nr_lines[0] }}"
      
    - name: check if the process wd.sap<sid>_W<nr> process is running
      debug:
        msg: "{{ ps_ef_ouptut }}"
      when: "ws_sap in ps_ef_ouptut.stdout_lines"

    - meta: end_play
      
    - name: Fail message when Status is not GREEN
      fail:
        msg: "wd.sap{{ SID|lower }}_W{{ instance_nr_lines[0] }} is not running"
      when: '"wd.sap{{ SID|lower }}_W{{ instance_nr_lines[0] }}" not in ps_ef_ouptut.stdout_lines'
      
    - name: cat available.log file
      shell: "cat available.log"
      args:
        chdir: "/usr/sap/{{ SID|upper }}/W{{ instance_nr_lines[0] }}/work/directory"
      register: available_log
      
    - debug: var=available_log
    
    - name: netstat command to check if the port is in use
      shell: "netstat -an | grep {{ webdispatcher_port }} 44300/ 44301"
