---
# [1] Create a virtual IP resource and health-probe for the ASCS instance

- name:                                "5.6 SCSERS - SUSE - SCS - Cluster Configuration before Install "
  throttle:                            1
  block:
    - name:                            "5.6 RHEL - SCS - Configure cluster default properties"
      ansible.builtin.shell: |
                                       pcs resource defaults resource-stickiness=1
                                       pcs resource defaults migration-threshold=3

    - name:                            "RHEL - SCS - Put Secondary host on standby"
      ansible.builtin.command:         pcs node standby {{ secondary_instance_name }}     


    - name:                            "5.6 SCSERS - RHEL - SCS - Configure File system resources"
      ansible.builtin.command: >
                                       pcs resource create fs_{{ sap_sid | upper }}_ASCS Filesystem \
                                       device='{{ sap_mnt }}/usrsap{{ sap_sid }}ascs' \
                                       directory='/usr/sap/{{ sap_sid | upper }}/ASCS{{ scs_instance_number }}' fstype='nfs' force_unmount=safe options='sec=sys,vers=4.1' \
                                       op start interval=0 timeout=60 \
                                       op stop interval=0 timeout=120 \
                                       op monitor interval=200 timeout=120 \
                                       --group g-{{ sap_sid | upper }}_ASCS
      register:                        ascs_fs_resource
      failed_when:                     ascs_fs_resource.rc > 1  

    - name:                            "5.6 SCSERS - RHEL - SCS - Create ASCS VIP - This is LB frontend ASCS/SCS IP"
      ansible.builtin.command: >
                                       pcs resource create vip_{{ sap_sid | upper }}_ASCS IPaddr2 \
                                       ip={{ scs_lb_ip }} cidr_netmask={{ subnet_prefix }} \
                                       --group g-{{ sap_sid | upper }}_ASCS
      register:                        ascs_vip
      failed_when:                     ascs_vip.rc > 1      

    - name:                            "5.6 SCSERS - RHEL - SCS - create Azure LB resource"
      ansible.builtin.command: >
                                       pcs resource create nc_{{ sap_sid | upper }}_ASCS azure-lb port=620{{ scs_instance_number }} \
                                       --group g-{{ sap_sid | upper }}_ASCS
      register:                        ascs_lb
      failed_when:                     ascs_lb.rc > 1

  when: inventory_hostname == primary_instance_name
  
# END of playbook.
...
