---
# [2] Create a virtual IP resource and health-probe for the ERS instance

- name:                                "5.6 SCSERS - SUSE - ERS - Cluster Configuration before Install"
  throttle:                            1
  block:
    - name:                            "5.6 SCSERS - ERS - Bring Secondary host online"
      ansible.builtin.command:         crm node online {{ secondary_instance_name }}
      register:                        secondary_online
      changed_when:                    secondary_online.rc != 0

    - name :                           "5.6 SCSERS - ERS - Put Primary host on standby"
      ansible.builtin.command:         crm node standby {{ primary_instance_name }}
      register:                        primary_standby
      changed_when:                    primary_standby.rc != 0

    - name:                            "5.6 SCSERS - ERS - Configure File system resources"
      ansible.builtin.command: >
                                       crm configure primitive fs_{{ sap_sid }}_ERS Filesystem \
                                       device='{{ sap_mnt }}/usrsap{{ sap_sid }}ers' \
                                       directory='/usr/sap/{{ sap_sid | upper }}/ERS{{ ers_instance_number }}' fstype='nfs' options='sec=sys,vers=4.1' \
                                       op start timeout="{{ cluster_sap_scs_timeouts.start }}" interval=0 \
                                       op stop timeout="{{ cluster_sap_scs_timeouts.stop }}"  interval=0 \
                                       op monitor interval="20s" timeout="40s"
      register:                        ers_fs_resource
      failed_when:                     ers_fs_resource.rc > 1

    - name:                            "5.6 SCSERS - ERS - Create ERS VIP - This is LB frontend ERS IP"
      ansible.builtin.command: >
                                       crm configure primitive vip_{{ sap_sid }}_ERS IPaddr2 \
                                       params ip={{ ers_lb_ip }} \
                                       op monitor interval="10s" timeout="20s"
      register:                        ers_vip
      failed_when:                     ers_vip.rc > 1


    - name:                            "5.6 SCSERS - ERS - create Azure LB resource "
      ansible.builtin.command:         crm configure primitive nc_{{ sap_sid }}_ERS azure-lb port=621{{ ers_instance_number }}
      register:                        ers_alb
      failed_when:                     ers_alb.rc > 1

    - name:                            "5.6 SCSERS - ERS - Create Health Probe"
      ansible.builtin.command: >
                                       crm configure group g-{{ sap_sid }}_ERS fs_{{ sap_sid }}_ERS nc_{{ sap_sid }}_ERS \
                                       vip_{{ sap_sid }}_ERS meta resource-stickiness=3000
      register:                        ers_hp
      failed_when:                     ers_hp.rc > 1
  when: inventory_hostname == secondary_instance_name

# END of playbook.