---
# [1] Create a virtual IP resource and health-probe for the ASCS instance

- name:                                "5.6 SCSERS - SUSE - SCS - Cluster Configuration before Install "
  throttle:                            1
  block:
    - name :                           "Put Secondary host on standby"
      ansible.builtin.command:         crm node standby {{ secondary_instance_name }}

    - name:                            "5.6 SCSERS - SCS - Configure File system resources"
      ansible.builtin.command: >
                                       crm configure primitive fs_{{ sap_sid }}_ASCS Filesystem \
                                       device='{{ sap_mnt }}/usrsap{{ sap_sid }}ascs' \
                                       directory='/usr/sap/{{ sap_sid | upper }}/ASCS{{ scs_instance_number }}' fstype='nfs' options='sec=sys,vers=4.1' \
                                       op start timeout="{{ cluster_sap_scs_timeouts.start }}" interval=0 \
                                       op stop timeout="{{ cluster_sap_scs_timeouts.stop }}"  interval=0 \
                                       op monitor interval="20s" timeout="40s"
      register:                        ascs_fs_resource
      failed_when:                     ascs_fs_resource.rc > 1



    - name:                            "5.6 SCSERS - SCS - Create ASCS VIP - This is LB frontend ASCS/SCS IP"
      ansible.builtin.command: >
                                       crm configure primitive vip_{{ sap_sid }}_ASCS IPaddr2 \
                                       params ip={{ scs_lb_ip }}  \
                                       op monitor interval="10s" timeout="20s"
      register:                        ascs_vip
      failed_when:                     ascs_vip.rc > 1

    - name:                            "5.6 SCSERS - SCS - create Azure LB resource"
      ansible.builtin.command:         crm configure primitive nc_{{ sap_sid }}_ASCS azure-lb port=620{{ scs_instance_number }}
      register:                        ascs_lb
      failed_when:                     ascs_lb.rc > 1

    - name:                            "5.6 SCSERS - SCS - Create Health Probe"
      ansible.builtin.command: >
                                       crm configure group g-{{ sap_sid }}_ASCS fs_{{ sap_sid }}_ASCS nc_{{ sap_sid }}_ASCS \
                                       vip_{{ sap_sid }}_ASCS meta resource-stickiness=3000
      register:                        ascs_hp
      failed_when:                     ascs_hp.rc > 1
  when: inventory_hostname == primary_instance_name
  
# END of playbook.
...