---
# [2] Create a virtual IP resource and health-probe for the ERS instance

- name:                                "5.6 SCSERS - SUSE - ERS - Cluster Configuration before Install"
  throttle:                            1
  block:

    - name:                            "5.6 SCSERS - RHEL - ERS - Put Secondary host on online"
      ansible.builtin.command:         pcs node unstandby {{ secondary_instance_name }}

    - name:                            "5.6 SCSERS - RHEL - ERS - Put Primary host on standby"
      ansible.builtin.command:         pcs node standby {{ primary_instance_name }}     

    - name:                            "5.6 SCSERS - RHEL - ERS - Set fact for ERS Filesystem"
      ansible.builtin.set_fact:
        ers_filesystem_device:        "/QP1APP/ERS02"

    - name:                            "5.6 SCSERS - RHEL - ERS - Configure File system resources"
      ansible.builtin.command: >
                                       pcs resource create fs_{{ sap_sid | upper }}_ERS Filesystem \
                                       device='{{ ers_filesystem_device }}' \
                                       directory='/usr/sap/{{ sap_sid | upper }}/ERS{{ ers_instance_number }}' fstype='nfs' force_unmount=safe options='sec=sys,vers=4.1' \
                                       op start interval=0 timeout=60 \
                                       op stop interval=0 timeout=120 \
                                       op monitor interval=200 timeout=105 \
                                       --group g-{{ sap_sid | upper }}_ERS
      register:                        ers_fs_resource
      failed_when:                     ers_fs_resource.rc > 1


    - name:                            "5.6 SCSERS - RHEL - ERS - Create ERS VIP - This is LB frontend ERS IP"
      ansible.builtin.command: >
                                       pcs resource create vip_{{ sap_sid | upper }}_ERS IPaddr2 \
                                       ip={{ ers_lb_ip }} cidr_netmask={{ subnet_prefix }} \
                                       --group g-{{ sap_sid | upper }}_ERS
      register:                        ers_vip
      failed_when:                     ers_vip.rc > 1

    - name:                            "5.6 SCSERS - RHEL - ERS - create Azure LB resource "
      ansible.builtin.command: >
                                       pcs resource create nc_{{ sap_sid | upper }}_ERS azure-lb port=621{{ ers_instance_number }} \
                                       --group g-{{ sap_sid | upper }}_ERS
      register:                        ers_alb
      failed_when:                     ers_alb.rc > 1



  when: inventory_hostname == secondary_instance_name

# END of playbook.
