---

# /*---------------------------------------------------------------------------8
# |                                                                            |
# |      Set Runtime Parameters - e.g Sub ID , Resource group name             |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

# ----------------------------------------
# BEGIN
# ----------------------------------------


- name:                                "SCSERS - Set the primary intance nic and secondary instance nic IP"
  ansible.builtin.set_fact:
    primary_instance_ip:               "{{ hostvars[primary_instance_name]['ansible_eth0']['ipv4']['address'] }}"
    secondary_instance_ip:             "{{ hostvars[secondary_instance_name]['ansible_eth0']['ipv4']['address'] }}"

- name:                                "SCSERS - Set the SCS and ERS Virtual Instance hostname"
  ansible.builtin.set_fact:
    scs_virtual_hostname:              "{{ sap_sid | lower }}scs{{ scs_instance_number }}vip1"
    ers_virtual_hostname:              "{{ sap_sid | lower }}ers{{ ers_instance_number }}vip2"

- name:                                "SCSERS - Print - Virtual Instance hostnames"
  ansible.builtin.debug:
    msg:
      - "The SCS Virtual hostname is {{ scs_virtual_hostname }}"
      - "The ERS Virtual hostname is {{ ers_virtual_hostname }}"
    verbosity:                         2


# - name:                                "SCSERS - Set the subnet prefix"
#   ansible.builtin.set_fact:
#     subnet_prefix: "{{ ((hostvars[ansible_hostname]['ansible_eth0']['ipv4']['address'] | string) + '/' +
#                         (hostvars[ansible_hostname]['ansible_eth0']['ipv4']['netmask'] | string)) | ansible.utils.ipaddr('prefix')
#      }}"




...
